Repository hcsp/produce-oom, pull requests merged in 2021-11, with the labels that each got.

#252 OutOfMemoryError异常
  src/main/java/com/github/hcsp/objectbasic/Main.java
Labels: is:answer

#253 out of memory heap
  src/main/java/com/github/hcsp/objectbasic/Main.java
Labels: from:VIP, is:answer

#254 1
  src/main/java/com/github/hcsp/objectbasic/Main.java
Labels: from:VIP, is:answer

#256 修改pom文件中重复声明plugin导致作业提交一定测试失败的问题
  pom.xml
Labels: from:VIP, is:enhancement

#259 故意用尽内存
  src/main/java/com/github/hcsp/objectbasic/Main.java
Labels: from:VIP, is:answer

#260 overloadingerror
  src/main/java/com/github/hcsp/objectbasic/Main.java
Labels: from:VIP, is:answer
